version: "3.8"
services:
  
  childdb:
    container_name: childdb
    restart: always
    ports:
      - 27018:27017
    volumes:
      - childdb_volume:/data/db
  child.api:
    container_name: ChildAPI
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
      - MongoDbConnectionSettings:ConnectionString=mongodb://childdb:27017
    depends_on:
      - childdb
    ports:
      - "5106:80"
      - "7106:80"


  childparentsdb:
    container_name: ChildParentsDb
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - childparentsdb_volume:/data/db
  childparents.api:
    container_name: ChildParentsAPI
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
      - MongoDbConnectionSettings:ConnectionString=mongodb://childparentsdb:27017
    depends_on:
      - childparentsdb
    ports:
      - "7103:80"
      - "5103:80"


  childsiblingsdb:
    container_name: ChildSiblingsDb
    restart: always
    ports:
      - 27022:27017
    volumes:
      - childsiblingsdb_volume:/data/db
  childsiblings.api:
    container_name: ChildSiblingsAPI
    restart: always
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.data.mongodb.uri=mongodb://childsiblingsdb:27017
    ports:
      - 8000:8000
    depends_on:
      - childsiblingsdb


  genderdb:
    container_name: GenderDb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - genderdb_volume:/data/db
  gender.api:
    container_name: GenderAPI
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
      - MongoDbConnectionSettings:ConnectionString=mongodb://genderdb:27017
    depends_on:
      - genderdb
    ports:
      - "5165:80"
      - "7165:80"


  questiondb:
    container_name: QuestionDb
    restart: always
    ports:
      - "27024:27017"
    volumes:
      - questiondb_volume:/data/db
  question.api:
     container_name: QuestionAPI 
     restart: always
     environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.data.mongodb.uri=mongodb://questiondb:27017
     ports:
      - 8002:8002
     depends_on:
     - questiondb


  questionanswerdb:
    container_name: QuestionAnswerDb
    restart: always
    ports:
      - "27025:27017"
    volumes:
      - questionanswerdb_volume:/data/db
  questionanswer.api:
    container_name: QuestionAnswerAPI
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
      - MongoDbConnectionSettings:ConnectionString=mongodb://questionanswerdb:27017
    depends_on:
      - questionanswerdb
    ports:
      - "7076:80"
      - "5076:80"


  questiontitledb:
    container_name: QuestionTitleDb
    restart: always
    ports:
      - "27023:27017"
    volumes:
      - questiontitledb_volume:/data/db
  questiontitle.api:
    container_name: QuestionTitleAPI
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
      - MongoDbConnectionSettings:ConnectionString=mongodb://questiontitledb:27017
    depends_on:
      - questiontitledb
    ports:
      - "7013:80"
      - "5013:80"


  educationstatusdb:
    container_name: EducationStatusDb
    restart: always
    ports:
      - "27021:27017"
    volumes:
      - educationstatusdb_volume:/data/db
  educationstatus.api:
    container_name: EducationStatusAPI
    restart: always
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.data.mongodb.uri=mongodb://educationstatusdb:27017
    ports:
      - 8001:8001
    depends_on:
      - educationstatusdb


  childmaterializedviewdb:
    container_name: ChildMaterializedViewDb
    restart: always
    user: root
    ports:
      - "1433:1433"
    volumes:
      - childmaterializedview_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12*
  childmaterializedview.api:
    container_name: ChildMaterializedViewAPI
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
      - "ConnectionStrings:SQLConnectionString=Server=childmaterializedviewdb,1433;Database=ChildMaterializedView2;User=sa;Password=Password12*"
    depends_on:
      - childmaterializedviewdb
    ports:
      - "5135:80"


  adultfamilyservicedb:
    container_name: AdultFamilyServiceDb
    restart: always
    ports:
      - "27034:27017"
    volumes:
      - adultfamilyservice_volume:/data/db
  adultfamilyservice.api:
    container_name: AdultFamilyServiceAPI
    restart: always
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.data.mongodb.uri=mongodb://adultfamilyservicedb:27017
    ports:
      - 9004:9004
    depends_on:
      - adultfamilyservicedb 


  adultquestiontitledb:
    container_name: AdultQuestionTitleDb
    restart: always
    ports:
      - "27031:27017"
    volumes:
      - adultquestiontitle_volume:/data/db
  adultquestiontitle.api:
    container_name: AdultQuestionTitleApi
    restart: always
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.data.mongodb.uri=mongodb://adultquestiontitledb:27017
    ports:
      - 9001:9001
    depends_on:
      - adultquestiontitledb      

  adultquestiondb:
    container_name: AdultQuestionDb
    restart: always
    ports:
      - "27032:27017"
    volumes:
      - adultquestion_volume:/data/db
  adultquestion.api:
    container_name: AdultQuestionApi
    restart: always
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.data.mongodb.uri=mongodb://adultquestiondb:27017
    ports:
      - 9002:9002
    depends_on:
      - adultquestiondb      

  adultquestionanswerdb:
    container_name: AdultQuestionAnswerDb
    restart: always
    ports:
      - "27033:27017"
    volumes:
      - adultquestionanswer_volume:/data/db
  adultquestionanswer.api:
    container_name: AdultQuestionAnswerApi
    restart: always
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.data.mongodb.uri=mongodb://adultquestionanswerdb:27017
    ports:
      - 9003:9003
    depends_on:
      - adultquestionanswerdb

  marriedstatusdb:
    container_name: MarriedStatusDb
    restart: always
    ports:
      - "27035:27017"
    volumes:
      - marriedstatus_volume:/data/db
  marriedstatus.api:
    container_name: MarriedStatusApi
    restart: always
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.data.mongodb.uri=mongodb://marriedstatusdb:27017
    ports:
      - 9005:9005
    depends_on:
      - marriedstatusdb


  adultviewdb:
    container_name: AdultViewDb
    restart: always    
    user: root
    ports:
      - "3306:3306"
    volumes:
      - adultview_volume:/var/lib/mysql  
    environment:
     - MYSQL_ROOT_PASSWORD=Password12*
     - MYSQL_DATABASE=adult-view
  adultview.api:
   container_name: AdultViewAPI
   restart: always
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - RabbitMQUrl=rabbitmq
    - "ConnectionStrings:MySQLConnectionString=Server=adultviewdb,3306;Database=adult-view;User=root;Password=Password12*"
   depends_on:
    - adultviewdb
   ports:
    - "5185:80" 


  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456